name: Deploy Kinesis Pipeline

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region to deploy to"
        required: true
        default: "ap-southeast-2"
      deployS3:
        description: "Deploy AWS S3s?"
        required: true
        default: "false"
      deployVPC:
        description: "Deploy AWS VPC?"
        required: true
        default: "false"
      deployMlPipeline:
        description: "Deploy AWS ML Pipeline?"
        required: true
        default: "false"
      deployRealTimePipeline:
        description: "Deploy AWS Real Time Pipeline?"
        required: true
        default: "false"
jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 1.6.0
      TF_VAR_lambda_architecture: "x86_64"
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Lambda Packages
        working-directory: modules/lambda
        run: |
          chmod +x create_package.sh
          ./create_package.sh

      - name: Glue package wheels
        working-directory: modules/glue-job
        run: |
          echo "=== Creating wheels ==="
          ./create_wheel.sh

          echo "=== Wheels created ==="
          ls -la wheels/

          # Get the actual wheel filename and update the environment variable
          ACTUAL_SKLEARN_WHEEL=$(ls wheels/scikit_learn-*.whl | head -1 | xargs basename)
          echo "ACTUAL_SKLEARN_WHEEL=$ACTUAL_SKLEARN_WHEEL" >> $GITHUB_ENV
          echo "TF_VAR_sklearn_wheel_filename=$ACTUAL_SKLEARN_WHEEL" >> $GITHUB_ENV

          echo "Using wheel: $ACTUAL_SKLEARN_WHEEL"

      - name: Terraform init
        working-directory: environments/dev
        run: |
          terraform init

      - name: Deploy S3
        if: ${{ github.event.inputs.deployS3 == 'true' }}
        working-directory: environments/dev
        run: |
          terraform plan -target=module.s3
          terraform apply -auto-approve

      - name: Deploy VPC
        if: ${{ github.event.inputs.deployVPC == 'true' }}
        working-directory: environments/dev
        timeout-minutes: 10 # Add timeout
        continue-on-error: false # Ensure errors are shown
        run: |
          set -e  # Exit on any error
          set -x  # Show commands being executed

          terraform plan -target=module.vpc
          terraform apply -auto-approve -target=module.vpc

      - name: Deploy Glue Job, DynamoDB, Sagemaker Endpoint, Step Functions
        if: ${{ github.event.inputs.deployMlPipeline == 'true' }}
        working-directory: environments/dev
        run: |
          terraform plan -target=module.glue_job -target=module.dynamodb -target=module.step_functions
          terraform apply -auto-approve

      - name: Execute Step Functions
        if: ${{ github.event.inputs.deployMlPipeline == 'true' }}
        run: |
          make execute-step-function

      - name: Deploy Lambda and API Gateway
        if: ${{ github.event.inputs.deployRealTimePipeline == 'true' }}
        working-directory: environments/dev
        run: |
          terraform plan -target=module.lambda -target=module.api_gateway
          terraform apply -auto-approve

      - name: Deploy Kinesis Pipeline
        if: ${{ github.event.inputs.deployRealTimePipeline == 'true' }}
        working-directory: environments/dev
        run: |
          terraform plan -target=module.kinesis -target=module.lambda -target=module.api_gateway
          terraform apply -auto-approve

      - name: Deploy Webapp and Cloudfront
        if: ${{ github.event.inputs.deployRealTimePipeline == 'true' }}
        working-directory: environments/dev
        run: |
          terraform plan -target=module.cloudfront -target=module.s3_webapp
          terraform apply -auto-approve

      - name: Update API URL and Webapp
        if: ${{ github.event.inputs.deployRealTimePipeline == 'true' }}
        run: |
          make update-api-url
          make deploy-webapp

      - name: Debug Terraform State
        working-directory: environments/dev
        run: |
          echo "=== Terraform State ==="
          terraform state list || echo "No state found"

          echo "=== Terraform Workspace ==="
          terraform workspace show

          echo "=== Backend Configuration ==="
          cat .terraform/terraform.tfstate 2>/dev/null || echo "No backend state file"
