name: Deploy Kinesis Pipeline

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region to deploy to"
        required: true
        default: "ap-southeast-2"
      deployResource:
        description: "Deploy AWS resources?"
        required: true
        default: "false"
jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 1.6.0
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}
    
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Terraform init
        run: |
          cd environments/dev
          terraform init
          cd ../..

      - name: Deploy Kinesis Pipeline
        if: ${{ github.event.inputs.deployResource == 'true' }}
        run: |
          cd environments/dev
          terraform init
          terraform plan
          terraform apply -auto-approve
          cd ../..

      - name: Update API URL and deploy Webapp
        run: |
          make update-api-url
          make deploy-webapp
